### ISSUE TITLE
GeoPandas 0.3 and matplotlib 2 dependency/build on conda-forge

### ISSUE THREAD

**Issue by emiliom** [geohackweek/vector#17] opened 2017-09-19 21:14 UTC
@ocefpaf: when @lsetiawan and I were putting together the GeoHackweek vector tutorial, we ran into an odd situation with the conda environment build (Py 3.6). At one point about two weeks ago, @lsetiawan created a conda env using our ["vectorenv" environment.yml](https://github.com/geohackweek/tutorial_contents/blob/master/vector/environment.yml), and the environment was created with `matplotlib 2.0`, as expected (in `GeoPandas 0.3`, default styles have been tuned to take advantage of matplotlib 2 defaults). But the following week, the same environment file on the same system led to an env that had `matplotlib 1.5` instead! We had to go with that on the vector notebooks (eg, [geopandas intro](http://nbviewer.jupyter.org/github/geohackweek/tutorial_contents/blob/master/vector/notebooks/geopandas_intro.ipynb)), mitigating its style defaults. 

We haven't tried creating an environment recently, so I don't know if the problem is fixed. @lsetiawan, do you know? @ocefpaf, if this problem is still happening, can you look into it? Do you know how that "regression" happened? Thanks!

**Comment by ocefpaf** [comment] 2017-09-19 22:00
The `conda` solver has some idiosyncrasies... The conda-forge `qt 5` package got an update and added some extra dependencies and `conda`, instead of downloading those dependencies, "wiggle" its way out by downgrading some of packages. (Horrible behavior but they insist the solver is perfect, that is a feature and not a bug, and we are packaging thing wrong :unamused:)

The only way out of this is to force more "metadata" in the `environment.yaml` file by adding `matplotlib=2` to the list. The channel preference sometimes helps but not always, so I would also add it to the file. Here is my version that works:

```yaml
name: vectorenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - geopandas
  - geojson
  - pysal
  - pyepsg
  - rasterstats
  - requests
  - folium
  - seaborn
  - jupyter
  - matplotlib=2
```

**Comment by emiliom** [comment] 2017-09-19 22:05
> The only way out of this is to force more "metadata" in the environment.yaml file by adding matplotlib=2 to the list. The channel preference sometimes helps but not always, so I would also add it to the file. Here is my version that works:

We can live with this. Thanks.

**Comment by ocefpaf** [comment] 2017-09-19 22:10
I forgot to mention that when we move to `conda-build 3` (conda-forge is currently using `conda-build 2`) this should be fixed. IMO the fix does not belong in the package, but rather in the solver, but that is the fix we will have...

**Closed as completed** 2018-09-05 06:12 UTC
